services:
  main:
    environment:
      DATABASE_URL: mysql://root:6003@mysql:3306/eco
    env_file:
      - apps/server/.env.test
    command: sh -c "pnpm run migrate && pnpm run seed && pnpm run test"
