services:
  mysql:
    environment:
      MYSQL_DATABASE: "eco"

  main:
    environment:
      DATABASE_URL: mysql://root:6003@mysql:3306/eco

    volumes:
      - ./:/app

    env_file:
      - apps/server/.env.prod

    command: sh -c "pnpm run migrate && pnpm run test"

volumes:
  code:
