name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t eco:0.0 .

    - name: Running test
      run: docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --abort-on-container-exit
